---
- name: Create a file on OpenWrt with community.openwrt modules
  hosts: all
  gather_facts: false
  become: false
  # collections:
  #   - community.openwrt
  # roles:
  #   - community.openwrt.init
  vars:
    openwrt_test_file: /usr/share/rpcd/acl.d/homepage.json.txt
    openwrt_test_content: "test form ansible and semaphore {{ lookup('env', 'OPENWRT_PASS2') }}"
  tasks:
    - name: Create or update the file content
      community.openwrt.copy:
        dest: "{{ openwrt_test_file }}"
        content: "{{ openwrt_test_content }}\n"
        mode: "0644"

    # - name: Verify resulting file content
    #   community.openwrt.slurp:
    #     src: "{{ openwrt_test_file }}"
    #   register: openwrt_file_content

    # - name: Show resulting file content
    #   ansible.builtin.debug:
    #     msg: "{{ openwrt_file_content.content | b64decode | trim }}"
