---
- name: Create a file on OpenWrt with community.openwrt modules
  hosts: all
  gather_facts: false
  become: false
  # collections:
  #   - community.openwrt
  # roles:
  #   - community.openwrt.init
  vars:
    openwrt_etc_config_rpcd_file: /etc/config/rpcd1
    openwrt_etc_config_rpcd_content: |
      config login
        option username 'homepage'
        option password '{{ lookup('env', 'OPENWRT_PASS') }}'
        list read 'homepage'
    openwrt_homepage_json_file: /usr/share/rpcd/acl.d/homepage.json
    openwrt_homepage_json_content: |
      {
        "homepage": {
          "description": "Homepage widget",
          "read": {
            "ubus": {
              "network.interface.wan": ["status"],
              "network.interface.lan": ["status"],
              "network.device": ["status"],
              "system": ["info"]
            }
          }
        }
      }
  tasks:
    - name: Create or update the content of {{openwrt_homepage_json_file}} file
      community.openwrt.copy:
        dest: "{{ openwrt_homepage_json_file }}"
        content: "{{ openwrt_homepage_json_content }}"
        mode: "0644"

    - name: Add homepage login to rpcd
      community.openwrt.uci:
        autocommit: true
        command: section
        config: rpcd
        type: login
        find:
          username: 'homepage'
        value:
          username: 'homepage'
          password: '{{ lookup("env", "OPENWRT_PASS") }}'
          read:
            - 'homepage'
      # register: rpcd_homepage_login
      notify: Restart rpcd

  handlers:
    - name: Restart rpcd
      community.openwrt.service:
        name: rpcd
        state: restarted
